### ISSUE TITLE
QUESTION: pin usage

### ISSUE THREAD

**Issue by IraSch** [Bodmer/TFT_Touch#2]
I'm looking to use this library with your TFT_eSPI library on an OddWires ESP32. There are 4 pin defiinitions in your example:

DOUT, DIN, DCLK and DCS. 

Do DOUT, DIN and DCLK refer to the SPI pins MOSI, MISO and SCK? 

Thanks.

**Comment by Bodmer** [comment]
The touch library is built into TFT_eSPI, the TFT_Touch library is for AVR processors.

See the TFT_eSPI touch screen examples.

Post back is you need more help.

**Comment by IraSch** [comment]
Thank you. I didn't realize it was there.
